### ISSUE TITLE
IsConnected in async loop is big performance hog

### ISSUE THREAD

**Issue by tgd-git** [domjancik/VL.IO.Xbox360Controller#1]
hey there domj, i wondered why using this plugin was eating 30% of my CPU. then i found the async loop to be the issue. it seems it is not needed anyway, is it? the IsConnected works just fine on its own.
cool contrib anyway. was very surprised to see it on nuget when looking for something to get a playstation controller going. Thanks for that!

**Comment by domjancik** [comment]
It works fine but IIRC it is a fairly expensive operation and as such I thought it better be done async. Just not in the AsyncLoop that just runs as fast as it can and fully consumes the CPU thread 😀

Motzi also raised this issue, and solved it temporarily by adding a Sleep into the AsyncLoop.
![image](https://user-images.githubusercontent.com/9571934/82835315-ebcb4500-9ec3-11ea-9578-3d42c5790888.png)

I will update the nuget with this or maybe a timer triggering the operation. The Controller can also likely be Cached. It's really been ages since I did this 😅

So it works with Playstation controller as well? That's nice.

**Comment by tgd-git** [comment]
ok i see. regarding the ps controller you need middleware. there is http://ds4windows.com/ which hooks between with an extra driver and exposes the ps controler to the os. it ends up somehow seen as xbox controller by windows.

**Comment by domjancik** [comment]
Very cool, thanks!

**Comment by domjancik** [comment]
This issue should be fixed now.
Please try it out and open a new issue if there are any problems still, thanks!
